import Head from 'next/head'
import Image from 'next/image'
import Slider from '../components/carousel/Slider'
import TrendingProduct from '../components/trending/TrendingProduct'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Vin Marts </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.webp" />
      </Head>
      {/* <Slider /> */}
      <TrendingProduct />
      

    </div>
  )
}
